// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createButton, renderWith } from "obix-core-component";
export { createButton } from "obix-core-component";
export type { ButtonConfig, ButtonSize, ButtonState, ButtonType, ButtonVariant } from "obix-core-component";
export const renderButton = renderWith(createButton);
